# site
title: Amber Yang
theme: louie

baseurl: ""
url: amzoyang.github.io
favicon: "/assets/AmberYang.jpg"
g_analytics: UA-12345678-1

# bio
header: <font size="+2">Hi, I'm Amber Yang.</font>
desc: >
  <img src="/assets/AmberYang.jpg" alt="Girl in a jacket" width="150" height="150">

  <br><br>The majority of my time is spent thinking about creating a sustainable space environment for satellites as the founder at <a href="seertracking.com"><b>Seer Tracking</b></a>, which led me to be named <a href="https://www.forbes.com/profile/amber-yang/#2fae76dd32de"><b>Forbes 30 Under 30</b></a>.<br><br> In the past, I've worked as a Product Manager at <b>Facebook</b> and a research scientist at <b>MIT Lincoln Laboratory</b>. <br><br>I'm a Computer Science and Physics student at <b>Stanford</b> and spent a quarter abroad studying Philosophy at Oxford. I've also dabbled a bit in VC and am a partner at <b>Dorm Room Fund</b>.<br><br> I'm always open to chatting about space, philosophy, politics. The best way to reach me is at <a href = "mailto: amber.yang@seertracking.com"><b>amber.yang@seertracking.com</b></a> or Twitter!
  <br><br> <b>Currently Reading</b>: The Contrarian

# posts
date_format: "%Y"
post_title: Blog
post_date: Date
post_cat: Type

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
